import React,{useEffect,useState}from'react';
const bank=[
 {q:'Tell me about yourself and walk me through a project you are proud of.',type:'Behavioral',hint:'Use a concise background → project → impact structure.'},
 {q:'Design a URL shortener. Start by clarifying the requirements.',type:'System Design',hint:'Cover functional requirements, scale, IDs, storage, caching and trade-offs.'},
 {q:'Given an array, find the longest subarray with at most K distinct values.',type:'DSA',hint:'Explain the sliding-window invariant before coding.'},
 {q:'What is the difference between a process and a thread?',type:'CS Fundamentals',hint:'Compare memory, isolation, context switching and communication.'}
];
export default function MockInterview(){const[i,setI]=useState(0),[answers,setAnswers]=useState(['','','','']),[started,setStarted]=useState(false),[done,setDone]=useState(false),[time,setTime]=useState(2700),[paused,setPaused]=useState(false);useEffect(()=>{if(!started||done||paused)return;const t=setInterval(()=>setTime(v=>v>0?v-1:0),1000);return()=>clearInterval(t)},[started,done,paused]);const submit=()=>{setDone(true);setPaused(true)};if(!started)return <section className='mock-start panel'><span className='eyebrow'>AI-STYLE MOCK INTERVIEW</span><h2>Practice under interview conditions.</h2><p>4 rounds covering behavioral, system design, DSA and CS fundamentals. Progress through one interviewer prompt at a time.</p><div className='mock-meta'><span>45 min</span><span>4 questions</span><span>Instant rubric feedback</span></div><button onClick={()=>setStarted(true)}>Start mock interview →</button></section>;if(done){const filled=answers.filter(Boolean).length,score=Math.min(92,48+filled*10+Math.round(answers.reduce((a,x)=>a+Math.min(x.length,220)/22,0)));return <section className='results'><span className='eyebrow'>SESSION COMPLETE</span><h2>Mock interview results</h2><div className='grid three'><div className='panel'><h3>Overall score</h3><div className='score'>{score}%</div><p className='muted'>Based on answer completeness and coverage.</p></div><div className='panel'><h3>Strong areas</h3><p>Structured communication, requirement thinking and technical breadth.</p></div><div className='panel'><h3>Improve next</h3><p>Add clearer trade-offs, edge cases and measurable impact.</p></div></div><div className='panel feedback'><h3>Question-by-question feedback</h3>{bank.map((x,n)=><div key={x.type}><b>{n+1}. {x.type}</b><p>{answers[n]?`Response captured. ${x.hint}`:'No response captured.'}</p></div>)}</div><button onClick={()=>{setI(0);setAnswers(['','','','']);setDone(false);setStarted(false);setTime(2700)}}>Start another session</button></section>}
const m=String(Math.floor(time/60)).padStart(2,'0'),s=String(time%60).padStart(2,'0'),item=bank[i];return <section className='mock-session'><div className='mock-top'><div><span className='eyebrow'>QUESTION {i+1} OF {bank.length} · {item.type}</span><h2>{item.q}</h2></div><div className='timer'>{m}:{s}</div></div><div className='panel interviewer'><b>Interviewer</b><p>Take your time. Think aloud and explain your approach before jumping into details.</p></div><textarea className='mock-answer' value={answers[i]} onChange={e=>{const copy=[...answers];copy[i]=e.target.value;setAnswers(copy)}} placeholder='Type your answer here. In a voice-enabled version, this is where your transcript would appear…'/><div className='mock-actions'><button className='ghost' onClick={()=>setPaused(!paused)}>{paused?'Resume':'Pause'}</button><span className='muted'>Tip: {item.hint}</span><div>{i>0&&<button className='ghost' onClick={()=>setI(i-1)}>← Previous</button>}{i<bank.length-1?<button onClick={()=>setI(i+1)}>Next question →</button>:<button onClick={submit}>Finish interview</button>}</div></div></section>}
