export const companyTracks=[
{name:'Amazon',sourceType:'candidate_report',focus:['Requirements clarification','Scalability','Operational excellence','Trade-offs'],rounds:['HLD design','LLD design','Behavioral follow-up'],problems:[{id:'url-shortener',title:'Design a URL Shortener',track:'HLD',difficulty:'Easy',frequency:'Very frequent'},{id:'parking-lot',title:'Design a Parking Lot',track:'LLD',difficulty:'Easy',frequency:'Frequent'}]},
{name:'Google',sourceType:'candidate_report',focus:['Distributed systems','Data consistency','Large-scale reliability'],rounds:['System design','Deep technical follow-up'],problems:[{id:'url-shortener',title:'Design a URL Shortener',track:'HLD',difficulty:'Easy',frequency:'Frequent'},{id:'instagram',title:'Design a Photo Sharing Platform',track:'HLD',difficulty:'Medium',frequency:'Frequent'}]},
{name:'Microsoft',sourceType:'candidate_report',focus:['API design','Cloud scale','Maintainability'],rounds:['Design round','Object-oriented design'],problems:[{id:'parking-lot',title:'Design a Parking Lot',track:'LLD',difficulty:'Easy',frequency:'Frequent'},{id:'url-shortener',title:'Design a URL Shortener',track:'HLD',difficulty:'Easy',frequency:'Occasional'}]},
{name:'Uber',sourceType:'candidate_report',focus:['Geo-distribution','Real-time systems','Event processing'],rounds:['HLD','Domain deep dive'],problems:[{id:'instagram',title:'Design a Photo Sharing Platform',track:'HLD',difficulty:'Medium',frequency:'Frequent'},{id:'url-shortener',title:'Design a URL Shortener',track:'HLD',difficulty:'Easy',frequency:'Occasional'}]},
{name:'Atlassian',sourceType:'candidate_report',focus:['Product requirements','Collaboration systems','Clear trade-offs'],rounds:['System design','Coding/design'],problems:[{id:'splitwise',title:'Design an Expense Sharing App',track:'LLD',difficulty:'Medium',frequency:'Frequent'},{id:'parking-lot',title:'Design a Parking Lot',track:'LLD',difficulty:'Easy',frequency:'Frequent'}]}
];
const hld=[{question:'What are the functional and non-functional requirements?',rubric:['scope','latency','availability','consistency']},{question:'Estimate QPS, storage, bandwidth and peak traffic.',rubric:['assumptions','math','headroom']},{question:'Walk through the architecture and identify scaling bottlenecks.',rubric:['components','data flow','failure modes']},{question:'What changes at 10× and 100× scale?',rubric:['partitioning','caching','cost','consistency']}];
const lld=[{question:'Identify the core entities and their responsibilities.',rubric:['abstraction','cohesion','relationships']},{question:'Which interfaces and design patterns would you use?',rubric:['SOLID','patterns','extensibility']},{question:'How will you handle concurrency and invalid state transitions?',rubric:['thread safety','validation','edge cases']},{question:'How would you test the design?',rubric:['unit tests','integration','testability']}];
const dsa=[{question:'Clarify constraints and propose a brute-force solution.',rubric:['clarification','correctness','complexity']},{question:'Optimize the approach and explain the data structures used.',rubric:['optimization','data structures','complexity']},{question:'Walk through edge cases and a dry run.',rubric:['edge cases','communication','verification']},{question:'Discuss time and space complexity and possible alternatives.',rubric:['analysis','trade-offs','alternatives']}];
export const mockQuestions={HLD:hld,LLD:lld,DSA:dsa};
