import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import {problems,users,state} from './data.js';
import {companyTracks,mockQuestions} from './companyTracks.js';
const app=express(); const PORT=process.env.PORT||4000; const SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
app.use(cors()); app.use(express.json());
const key=id=>String(id); const findUser=id=>[...users.values()].find(x=>x.id===id);
function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace('Bearer ',''),SECRET);next()}catch{return res.status(401).json({error:'Unauthorized'})}}
function publicProblem(p,user){const allowed=!p.premium||user?.plan==='premium';return {...p,solution:allowed?p.solution:undefined,locked:!allowed};}
app.get('/health',(req,res)=>res.json({ok:true}));
app.post('/api/auth/register',async(req,res)=>{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'name, email and password required'});if(users.has(email))return res.status(409).json({error:'User exists'});const user={id:crypto.randomUUID(),name,email,passwordHash:await bcrypt.hash(password,10),plan:'free',createdAt:new Date().toISOString()};users.set(email,user);const token=jwt.sign({id:user.id,email,plan:user.plan},SECRET,{expiresIn:'7d'});res.status(201).json({token,user:{id:user.id,name,email,plan:user.plan}})});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body,user=users.get(email);if(!user||!await bcrypt.compare(password,user.passwordHash))return res.status(401).json({error:'Invalid credentials'});const token=jwt.sign({id:user.id,email,plan:user.plan},SECRET,{expiresIn:'7d'});res.json({token,user:{id:user.id,name:user.name,email,plan:user.plan}})});
app.get('/api/profile',auth,(req,res)=>{const u=findUser(req.user.id);res.json({id:u.id,name:u.name,email:u.email,plan:u.plan})});
app.get('/api/subscription',auth,(req,res)=>res.json({plan:req.user.plan,isActive:req.user.plan==='premium'}));
app.post('/api/demo/plan',auth,(req,res)=>{const u=findUser(req.user.id);u.plan=req.body.plan==='premium'?'premium':'free';res.json({plan:u.plan})});
app.get('/api/problems',auth,(req,res)=>res.json(problems.map(p=>publicProblem(p,findUser(req.user.id)))));
app.get('/api/problems/:id',auth,(req,res)=>{const p=problems.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Not found'});res.json(publicProblem(p,findUser(req.user.id)))});
app.get('/api/companies',auth,(req,res)=>res.json(companyTracks));
app.get('/api/companies/:name',auth,(req,res)=>{const c=companyTracks.find(x=>x.name.toLowerCase()===req.params.name.toLowerCase());if(!c)return res.status(404).json({error:'Company track not found'});res.json({...c,problems:c.problems.map(id=>publicProblem(problems.find(p=>p.id===id),findUser(req.user.id)))})});
app.post('/api/mock/start',auth,(req,res)=>{const track=req.body.track||'HLD';const id=crypto.randomUUID();const sessions=state.mockSessions||new Map();state.mockSessions=sessions;sessions.set(id,{id,userId:req.user.id,track,index:0,startedAt:Date.now(),answers:[]});res.json({sessionId:id,question:mockQuestions[0],remaining:mockQuestions.length})});
app.post('/api/mock/:id/answer',auth,(req,res)=>{const s=state.mockSessions?.get(req.params.id);if(!s||s.userId!==req.user.id)return res.status(404).json({error:'Session not found'});s.answers.push({question:mockQuestions[s.index],answer:req.body.answer||'',at:Date.now()});s.index++;if(s.index>=mockQuestions.length){const answered=s.answers.filter(x=>x.answer.trim()).length;const score=Math.round((answered/mockQuestions.length)*100);return res.json({done:true,score,feedback:score>=75?'Good structure. Add more explicit trade-offs and failure modes.':'Cover requirements, estimates, architecture and trade-offs more systematically.'})}res.json({done:false,question:mockQuestions[s.index],remaining:mockQuestions.length-s.index})});
app.get('/api/bookmarks',auth,(req,res)=>res.json([...(state.bookmarks.get(key(req.user.id))||new Set())]));
app.post('/api/bookmarks/:id',auth,(req,res)=>{const id=key(req.user.id),set=state.bookmarks.get(id)||new Set();set.has(req.params.id)?set.delete(req.params.id):set.add(req.params.id);state.bookmarks.set(id,set);res.json({bookmarked:set.has(req.params.id)})});
app.get('/api/progress',auth,(req,res)=>res.json([...(state.progress.get(key(req.user.id))||new Map()).values()]));
app.put('/api/progress/:id',auth,(req,res)=>{const id=key(req.user.id),m=state.progress.get(id)||new Map(),value={problemId:req.params.id,status:req.body.status||'in_progress',updatedAt:new Date().toISOString()};m.set(req.params.id,value);state.progress.set(id,m);res.json(value)});
app.get('/api/workspaces/:id',auth,(req,res)=>res.json(state.workspaces.get(key(req.user.id)+':'+req.params.id)||{nodes:[],edges:[],notes:''}));
app.put('/api/workspaces/:id',auth,(req,res)=>{const value={nodes:req.body.nodes||[],edges:req.body.edges||[],notes:req.body.notes||'',updatedAt:new Date().toISOString()};state.workspaces.set(key(req.user.id)+':'+req.params.id,value);res.json(value)});
app.listen(PORT,()=>console.log(`InterviewForge API listening on ${PORT}`));